[build-system]
requires = [
    "cmake",
    "clang",
    "ninja",
    "numpy",
    "packaging",
    "pybind11",
    "PyYAML",
    "setuptools",
    "wheel",
]
build-backend = "setuptools.build_meta"
